project:
  type: website
  output-dir: docs

website:
  title: "ToB213"
  open-graph: true
  twitter-card: true
  site-url: https://tob213.github.io
  repo-url: https://github.com/ToB213/Tob213.github.io
  issue-url: https://github.com/ToB213/ToB213.github.io/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  page-footer:
    left: Niimi syunya
    center:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: twitter
        href: https://x.com/just_for_ToB
        aria-label: ToB213 Twitter
      - icon: github
        href: https://tob213.github.io
        aria-label: ToB213 GitHub
  navbar:
    background: dark
    title: ToB213
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/ToB213/ToB213.github.io/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/ToB213/ToB213.github.io/discussions"
    tools:
      - icon: twitter
        href: https://x.com/just_for_ToB
        text: ToB213 Twitter
      - icon: github
        href: https://github.com/ToB213/
        text: ToB213 GitHub

format:
  html:
    toc: true
    theme:
      light: [sketchy, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
editor: visual

